version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=///Killer2stz
      - POSTGRES_DB=strapi-code-demy
      - DATABASE_USERNAME=postgres
    ports:
      - 5432:5432
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    networks:
      - strapi_network

  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
    ports:
      - 1337:1337
    networks:
      - strapi_network

networks:
  strapi_network:
    driver: bridge


#sudo docker compose -p sun-academy up -d