version: '3.8'
services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 1337:1337
    expose:
      - 1337
    networks:
      - strapi_network
networks:
  strapi_network:
    driver: bridge
    
#sudo docker compose -p sun-academy up -d
